### ISSUE TITLE
Conditional tag styles for overdue due dates broken?

### ISSUE THREAD

**Issue by jacobsamlarose** [mutahhir/foldingtext-issues#6]
A plugin based on the code from this thread: http://support.foldingtext.com/t/conditional-tag-styles/437/4

no longer works. Overdue tasks are no longer rendered with conditional styling.

**Comment by mutahhir** [comment]
Can you paste in (or create a [gist](https://gist.github.com/)) the code for the plugin? and also let me know if you can see any errors in the 'SDK' inspector when you use the plugin. (You can see that by going to Help > Software Development Kit, then click on 'Run editor' link, and click on Inspector toolbar item)

**Comment by jacobsamlarose** [comment]
## MAIN.JS

```
              define(function (require, exports, module) {
              'use strict';

              var Extensions = require('ft/core/extensions').Extensions,
                NodeSet = require('ft/core/nodeset').NodeSet,
                DateUtils = require('ft/util/date'),
                dueNodes = new NodeSet();

              /*jshint multistr:true */
              Extensions.add('com.foldingtext.editor.styles',
                '.cm-overdue {\
                  background: red;\
                }'
              );
              /*jshint multistr:false */

              Extensions.addRenderNodeElementStyles(function (editor, node, elementRenderer) {
                if (dueNodes.containsNode(node)) {
                  elementRenderer.addWrapClass('cm-overdue');
                }
              });

              Extensions.add('com.foldingtext.editor.clockTick', function (editor, clockDate) {
                var nodePath = '//@due < "' + clockDate.format('isoDate') + '"',
                  newDueNodes = NodeSet.setFromArray(editor.tree().evaluateNodePath(nodePath)),
                  removedFromDue = NodeSet.minusSets(dueNodes, newDueNodes),
                  addedToDue = NodeSet.minusSets(newDueNodes, dueNodes);

                removedFromDue.forEachNodeInSet(function(each) {
                  editor.setNeedsRender(each);
                });

                addedToDue.forEachNodeInSet(function(each) {
                  editor.setNeedsRender(each);
                });

                dueNodes = newDueNodes;    
              });
            });
```

## ERRORS FROM SDK INSPECTOR

"Failed to load resource: The requested URL was not found on this server."
file:///Applications/FoldingText.app/Contents/Resources/dist/sdk/sources/ft/util/date.js

**Comment by mmzsource** [comment]
Same error here. Tried to fix it by removing foldingtext and installing it again. Still the same error. I don't mind adding the required date.js to the specified folder. Where can I download it?

**Comment by mmzsource** [comment]
Checked the main.js files of my plugins to find out which plugin needs the date.js. Turns out my 'date and time' plugin required date.js and the 'stopwatch' plugin requires it. 

Looked up the plugins on github. Noticed that the 'date and time' plugin was updated 8 days ago. It no longer requires date.js. Changed my 'date time' main.js file accordingly and regained the commands to add date and time in foldingtext. (they were gone before changing the main.js).

However, the stopwatch plugin (which seems to be working ok, by the way) also requires the date.js file. So that plugin might be causing the error in the debugger. (I'm still not sure why date.js wasn't included in my foldingtext.app in the '/Applications/FoldingText.app/Contents/Resources/dist/sdk/sources/ft/util' folder in the first place though).

**Comment by mmzsource** [comment]
I've been investigating the error a little further because I noticed my list of run commands seemed to be changing between foldingtext app usage. For instance, sometimes the 'informal dates and adjustments' command was available, sometimes not. (this plugin allows me to insert a date informally). A trail of my debugging session:

**Investigation:**
- I noticed an error loading a date.js dependency in the console log
- In the resources tab of the debugger I noticed a Red colored date.js 
- I noticed the 'stopwatch' plugins is the only plugin requiring date.js
- In the resources tab of the debugger I noticed a stopwatchmode.js which didn't seem to require date.js
- The plugin manager showed no errors or warnings

**Experiment:**
- I disabled the old stopwatch plugin, because it didn't seem to be needed for the stopwatch functionality (stopwatchmode.js seems to take care of it) while the old stopwatch plugin _did_ produce an error.

**Result:** 
- date.js was no longer required (not mentioned as missing in resources, no longer an error message)
- the 'informal dates and adjustments' command shows up every time (up until now)
- stopwatch functionality still working

**Hypothesis:**
- Updating the app does not update the plugins
- Sometimes a plugin still relies on a file which was available in the previous app version, but not anymore in the new version
- therefore the loading of one or more plugins fails (silently; no errors in the plugin manager)
- it seems like failing to load one plugin influences the loading of another plugin because the 'informal dates and adjustments' command is loaded every time since the change, while before, it was almost never loaded.

Hope this helps. Would like to hear your thoughts.

**Comment by mutahhir** [comment]
@mmzsource True, the plugins are separate from the main app. I think they have been updated now and most should work without problems now. There was a problem with the date lib being removed as you mentioned in your comment.

Moving forward, I think there should be more errors shown by FoldingText about such errors, but the plugins architecture is the most unknown to me right now. I'll be making progress gradually though, so please feel free to open issues here as you see them.

Going to close this one for now as this seems to be resolved. Feel free to reopen if I'm mistaken.

**Comment by jacobsamlarose** [comment]
I'm a little frustrated here. Based on what I've read here, I'd updated the script I'd posted above (commented out the `DateUtils = require('ft/util/date'),` line) and got highlighting of overdue tasks working again. I've just noticed today that highlighting no longer works, presumably since the last update. 

I've made sure to update core plugins. Checking the SDK document inspector returns the following error: 

[Error] TypeError: clockDate.format is not a function. (In 'clockDate.format('isoDate')', 'clockDate.format' is undefined)
    (anonymous function)
    (anonymous function)
    processExtensions
    (anonymous function)
    runInOp
    operation
    operation
    onTimeout

"clockDate.format" is called upon by the Conditional Tag Styles plugin. I'm not sure what to replace that function with. Was clockDate defined in date.js?
